version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  of-echo:
    lang: python3-http
    handler: ./echo
    image: embano1/of-echo:latest
    environment:
      write_debug: true
      read_debug: true
    annotations:
      topic: "DrsVmPoweredOnEvent,VmPoweredOnEvent,VmPoweredOffEvent"
